-- CREATE DATABASE Datanest;

USE Datanest; 


SELECT DB_name() AS Current_Database;



CREATE TABLE DATASETS (
    DATASET_ID INT IDENTITY(1,1) PRIMARY KEY,

    DATASET_NAME VARCHAR(100) NOT NULL,

    SOURCE_TYPE VARCHAR(20) NOT NULL,

    FILE_NAME VARCHAR(255) NULL,

    CREATED_AT SMALLDATETIME NOT NULL DEFAULT GETDATE(),

    UPDATED_AT SMALLDATETIME NOT NULL DEFAULT GETDATE(),

    ROW_COUNT INT NOT NULL DEFAULT 0,

    COLUMN_COUNT INT NOT NULL DEFAULT 0,

    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    CONSTRAINT CK_DATASETS_ROW_COUNT
        CHECK (ROW_COUNT >= 0),

    CONSTRAINT CK_DATASETS_COLUMN_COUNT
        CHECK (COLUMN_COUNT >= 0),

    CONSTRAINT CK_DATASETS_SOURCE_TYPE
        CHECK (SOURCE_TYPE IN ('CSV', 'EXCEL', 'TALLY', 'MSSQL')),

    CONSTRAINT CK_DATASETS_STATUS
        CHECK (STATUS IN ('PENDING', 'PROCESSING', 'READY', 'FAILED'))
);


-- INSERT INTO DATASETS (
--     DATASET_NAME,
--     SOURCE_TYPE,
--     FILE_NAME,
--     ROW_COUNT,
--     COLUMN_COUNT,
--     STATUS
-- )
-- VALUES (
--     'SALES',
--     'CSV',
--     'sales_1.csv',
--     1245,
--     10,
--     'READY'
-- );


-- SELECT * FROM DATASETS;

-- DELETE FROM DATASETS
-- WHERE DATASET_NAME = 'SALES'
--   AND FILE_NAME = 'sales_1.csv';

